name: Test GraphQL API

on: 
  push:
    branches:
      - Testing
  pull_request:
    branches:
      - Testing

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install NVM and Node.js on Linux
      if: runner.os == 'Linux'
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 20
        nvm use 20

    - name: Install NVM and Node.js on macOS
      if: runner.os == 'macOS'
      run: |
        brew install nvm
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 20
        nvm use 20
    
    - name: Set up working directory
      run: cd backend
      
    - name: Install dependencies
      run: npm install
      working-directory: backend

    - name: Refresh backend
      run: ./refresh.sh
      working-directory: backend

    - name: Start backend
      run: npm run start &
      working-directory: backend
      
    - name: Run tests
      run: npm run test
      working-directory: backend
